name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter pub get
            flutter build apk --release
          else
            find . -name "pubspec.yaml" -execdir flutter pub get \;
            find . -name "pubspec.yaml" -execdir flutter build apk --release \;
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: God_Agent_Console_v2
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
